# Site
title: Kruthika Virupakshappa
description: Data analyst & Data Scientist
url: https://Kruthika_Virupakshappa.github.io
baseurl: ""  # keep empty for user sites

# Profile / social
username: Your Name
user_title: Data Analyst
user_description: I love turning messy data into clear decisions.
email: you@example.com
github_username: your-username
twitter_username: yourhandle
# add/remove others as needed
